# Generated by Django 4.1.1 on 2022-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('profile_link', models.CharField(max_length=250, null=True)),
                ('image_url', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'collaborator',
            },
        ),
        migrations.AddIndex(
            model_name='collaborator',
            index=models.Index(fields=['name', 'first_name', 'last_name'], name='collaborator_name_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='collaborator_unique_key'),
        ),
    ]
